# Generated by Django 2.1.7 on 2019-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default='NOT CLAIMED', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='NO DESCRIPTION PROVIDED', max_length=600),
        ),
    ]
